<?php 
require_once ('mail_attachment.php');  

function Notify_Admin($message)
{
	NotifyAdminByEmail("Notification: Error Occurred!!", $message);
}

function Notify_User($title, $message, $returnaddress)
{
	echo ("<!DOCTYPE html> <html> <head> <link rel=\"stylesheet\" type=\"text/css\" href=\"/toolbox/bootstrap-3.3.5-dist/css/bootstrap.min.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"/css/style-home.css\" /> <script type=\"text/javascript\" language=\"javascript\" src=\"/toolbox/bootstrap-3.3.5-dist/js/bootstrap.min.js\"></script><style>.blink {animation: blink 1s steps(5, start) infinite;-webkit-animation: blink 1s steps(5, start) infinite;}@keyframes blink {to {visibility: hidden;}}@-webkit-keyframes blink {to {visibility: hidden;}} .alert{box-shadow: 10px 10px 5px #888888; z-index:9999999; background-image: url('./images/symphony.png'); background-position:left top; background-repeat:repeat; font-family: 'Open Sans', sans-serif; width: 478px; padding: 17px; border-radius: 5px; text-align: center; position: fixed; left: 50%; top: 50%; margin-left: -256px; margin-top: -200px; overflow: hidden;} h2{color:#575757;font-size:30px;text-align:center;font-weight:600;text-transform:none;position:relative;margin:25px 0;padding:0;line-height:25px;display:block; } p{color:#797979;font-size:16px;text-align:center;font-weight:300;position:relative;margin:0;padding:0;line-height:normal; } button { background-color:#AEDEF4; color:white; border:none; box-shadow:none; font-size:17px; font-weight:500; border-radius:5px; padding:10px 32px; margin:26px 5px 0 5px; cursor:pointer; } button:focus { outline:none; box-shadow:0 0 2px rgba(128, 179, 235, 0.5), inset 0 0 0 1px rgba(0, 0, 0, 0.05); } button:hover { background-color:#a1d9f2; } button:active { background-color:#81ccee; } </style> </head> <body style='background-color:gray'> <div class='alert'> <br/><br/> <i class=\"glyphicon glyphicon-ok-circle\" style='font-size:100px;color:#009933;'></i><br/> <h2>$title</h2> <p>$message</p> <button class='cancel' onclick='window.location.assign(\"$returnaddress\");'>OK</button> </div> </body> </html>");
}

function Error_User($title, $message, $returnaddress)
{
	echo ("<!DOCTYPE html> <html> <head> <link rel=\"stylesheet\" type=\"text/css\" href=\"/toolbox/bootstrap-3.3.5-dist/css/bootstrap.min.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"/css/style-home.css\" />  <script type=\"text/javascript\" language=\"javascript\" src=\"/toolbox/bootstrap-3.3.5-dist/js/bootstrap.min.js\"></script><style> .alert{box-shadow: 10px 10px 5px #888888; z-index:9999999; background-image: url('./images/symphony.png'); background-position:left top; background-repeat:repeat; font-family: 'Open Sans', sans-serif; width: 478px; padding: 17px; border-radius: 5px; text-align: center; position: fixed; left: 50%; top: 50%; margin-left: -256px; margin-top: -200px; overflow: hidden;} h2{color:#575757;font-size:30px;text-align:center;font-weight:600;text-transform:none;position:relative;margin:25px 0;padding:0;line-height:25px;display:block; } p{color:#797979;font-size:16px;text-align:center;font-weight:300;position:relative;margin:0;padding:0;line-height:normal; } button { background-color:#AEDEF4; color:white; border:none; box-shadow:none; font-size:17px; font-weight:500; border-radius:5px; padding:10px 32px; margin:26px 5px 0 5px; cursor:pointer; } button:focus { outline:none; box-shadow:0 0 2px rgba(128, 179, 235, 0.5), inset 0 0 0 1px rgba(0, 0, 0, 0.05); } button:hover { background-color:#a1d9f2; } button:active { background-color:#81ccee; } </style> </head> <body style='background-color:gray'> <div class='alert'> <br/><br/> <i class=\"glyphicon glyphicon-remove-circle\" style='font-size:100px;color:red;'></i><br/> <h2>$title</h2> <p>$message</p> <button class='cancel' onclick='window.location.assign(\"$returnaddress\");'>OK</button> </div> </body> </html>");
}


function Warning_User($title, $message, $returnaddress)
{
	echo ("<!DOCTYPE html> <html> <head> <link rel=\"stylesheet\" type=\"text/css\" href=\"/toolbox/bootstrap-3.3.5-dist/css/bootstrap.min.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"/css/style-home.css\" />  <script type=\"text/javascript\" language=\"javascript\" src=\"/toolbox/bootstrap-3.3.5-dist/js/bootstrap.min.js\"></script><style> .alert{box-shadow: 10px 10px 5px #888888; z-index:9999999; background-image: url('./images/symphony.png'); background-position:left top; background-repeat:repeat; font-family: 'Open Sans', sans-serif; width: 478px; padding: 17px; border-radius: 5px; text-align: center; position: fixed; left: 50%; top: 50%; margin-left: -256px; margin-top: -200px; overflow: hidden;} h2{color:#575757;font-size:30px;text-align:center;font-weight:600;text-transform:none;position:relative;margin:25px 0;padding:0;line-height:25px;display:block; } p{color:#797979;font-size:16px;text-align:center;font-weight:300;position:relative;margin:0;padding:0;line-height:normal; } button { background-color:#AEDEF4; color:white; border:none; box-shadow:none; font-size:17px; font-weight:500; border-radius:5px; padding:10px 32px; margin:26px 5px 0 5px; cursor:pointer; } button:focus { outline:none; box-shadow:0 0 2px rgba(128, 179, 235, 0.5), inset 0 0 0 1px rgba(0, 0, 0, 0.05); } button:hover { background-color:#a1d9f2; } button:active { background-color:#81ccee; } </style> </head> <body style='background-color:gray;'><div class='alert'> <br/><br/> <i class=\"glyphicon glyphicon-ban-circle\" style='font-size:100px;color:red;'></i><br/> <h2>$title</h2> <p>$message</p> <button class='cancel' onclick='window.location.assign(\"$returnaddress\");'>OK</button> </div></body> </html>");
}


function Notify_User_Then_HistoryBack($title, $message)
{
	echo ("<!DOCTYPE html> <html> <head> <link rel=\"stylesheet\" type=\"text/css\" href=\"/toolbox/bootstrap-3.3.5-dist/css/bootstrap.min.css\"> <script type=\"text/javascript\" language=\"javascript\" src=\"/toolbox/bootstrap-3.3.5-dist/js/bootstrap.min.js\"></script><style> .alert{box-shadow: 10px 10px 5px #888888; z-index:9999999; background-image: url('./images/symphony.png'); background-position:left top; background-repeat:repeat; font-family: 'Open Sans', sans-serif; width: 478px; padding: 17px; border-radius: 5px; text-align: center; position: fixed; left: 50%; top: 50%; margin-left: -256px; margin-top: -200px; overflow: hidden;} h2{color:#575757;font-size:30px;text-align:center;font-weight:600;text-transform:none;position:relative;margin:25px 0;padding:0;line-height:25px;display:block; } p{color:#797979;font-size:16px;text-align:center;font-weight:300;position:relative;margin:0;padding:0;line-height:normal; } button { background-color:#AEDEF4; color:white; border:none; box-shadow:none; font-size:17px; font-weight:500; border-radius:5px; padding:10px 32px; margin:26px 5px 0 5px; cursor:pointer; } button:focus { outline:none; box-shadow:0 0 2px rgba(128, 179, 235, 0.5), inset 0 0 0 1px rgba(0, 0, 0, 0.05); } button:hover { background-color:#a1d9f2; } button:active { background-color:#81ccee; } </style> </head> <body style='background-color:gray'> <div class='alert'> <br/><br/> <i class=\"glyphicon glyphicon-ok-circle\" style='font-size:100px;color:#009933;'></i><br/> <h2>$title</h2> <p>$message</p> <button class='cancel' onclick='javascript:window.history.back();'>OK</button> </div> </body> </html>");
}

function Warning_User_Then_HistoryBack($title, $message)
{
	echo ("<!DOCTYPE html> <html> <head> <link rel=\"stylesheet\" type=\"text/css\" href=\"/toolbox/bootstrap-3.3.5-dist/css/bootstrap.min.css\"> <script type=\"text/javascript\" language=\"javascript\" src=\"/toolbox/bootstrap-3.3.5-dist/js/bootstrap.min.js\"></script><style> .alert{box-shadow: 10px 10px 5px #888888; z-index:9999999; background-image: url('./images/symphony.png'); background-position:left top; background-repeat:repeat; font-family: 'Open Sans', sans-serif; width: 478px; padding: 17px; border-radius: 5px; text-align: center; position: fixed; left: 50%; top: 50%; margin-left: -256px; margin-top: -200px; overflow: hidden;} h2{color:#575757;font-size:30px;text-align:center;font-weight:600;text-transform:none;position:relative;margin:25px 0;padding:0;line-height:25px;display:block; } p{color:#797979;font-size:16px;text-align:center;font-weight:300;position:relative;margin:0;padding:0;line-height:normal; } button { background-color:#AEDEF4; color:white; border:none; box-shadow:none; font-size:17px; font-weight:500; border-radius:5px; padding:10px 32px; margin:26px 5px 0 5px; cursor:pointer; } button:focus { outline:none; box-shadow:0 0 2px rgba(128, 179, 235, 0.5), inset 0 0 0 1px rgba(0, 0, 0, 0.05); } button:hover { background-color:#a1d9f2; } button:active { background-color:#81ccee; } </style> </head> <body style='background-color:gray'> <div class='alert'> <br/><br/> <i class=\"glyphicon glyphicon-ban-circle\" style='font-size:100px;color:red;'></i><br/> <h2>$title</h2> <p>$message</p> <button class='cancel' onclick='javascript:window.history.back();'>OK</button> </div> </body> </html>");
}

function Error_User_Then_HistoryBack($title, $message)
{
	echo ("<!DOCTYPE html> <html> <head> <link rel=\"stylesheet\" type=\"text/css\" href=\"/toolbox/bootstrap-3.3.5-dist/css/bootstrap.min.css\"> <script type=\"text/javascript\" language=\"javascript\" src=\"/toolbox/bootstrap-3.3.5-dist/js/bootstrap.min.js\"></script><style> .alert{box-shadow: 10px 10px 5px #888888; z-index:9999999; background-image: url('./images/symphony.png'); background-position:left top; background-repeat:repeat; font-family: 'Open Sans', sans-serif; width: 478px; padding: 17px; border-radius: 5px; text-align: center; position: fixed; left: 50%; top: 50%; margin-left: -256px; margin-top: -200px; overflow: hidden;} h2{color:#575757;font-size:30px;text-align:center;font-weight:600;text-transform:none;position:relative;margin:25px 0;padding:0;line-height:25px;display:block; } p{color:#797979;font-size:16px;text-align:center;font-weight:300;position:relative;margin:0;padding:0;line-height:normal; } button { background-color:#AEDEF4; color:white; border:none; box-shadow:none; font-size:17px; font-weight:500; border-radius:5px; padding:10px 32px; margin:26px 5px 0 5px; cursor:pointer; } button:focus { outline:none; box-shadow:0 0 2px rgba(128, 179, 235, 0.5), inset 0 0 0 1px rgba(0, 0, 0, 0.05); } button:hover { background-color:#a1d9f2; } button:active { background-color:#81ccee; } </style> </head> <body style='background-color:gray'> <div class='alert'> <br/><br/> <i class=\"glyphicon glyphicon-remove-circle\" style='font-size:100px;color:red;'></i><br/> <h2>$title</h2> <p>$message</p> <button class='cancel' onclick='javascript:window.history.back();'>OK</button> </div> </body> </html>");
}
